// Gate-level netlist for cfg_bus — timed by PrimeTime against tiny.db
module cfg_bus (clk, cfg_in, mode_out, data_out);
  input clk;
  input cfg_in;
  output mode_out;
  output data_out;
  wire cfg_reg_q;
  wire mode_reg_d;
  wire data_reg_d;
  wire cfg_reg_qs_n0;
  wire cfg_reg_qs_n1;
  wire cfg_reg_qs_n2;
  wire cfg_reg_qs_n3;
  wire cfg_reg_qs_n4;
  wire cfg_reg_qs_n5;
  wire cfg_reg_qs_n6;
  wire cfg_reg_qs_n7;
  wire cfg_reg_dp_n0;
  DFFX1 cfg_reg (.D(cfg_in), .CK(clk), .Q(cfg_reg_q));
  DFFX1 mode_reg (.D(mode_reg_d), .CK(clk), .Q(mode_out));
  DFFX1 data_reg (.D(data_reg_d), .CK(clk), .Q(data_out));
  BUFX1 cfg_reg_qs_b0 (.A(cfg_reg_q), .Y(cfg_reg_qs_n0));
  BUFX1 cfg_reg_qs_b1 (.A(cfg_reg_qs_n0), .Y(cfg_reg_qs_n1));
  BUFX1 cfg_reg_qs_b2 (.A(cfg_reg_qs_n1), .Y(cfg_reg_qs_n2));
  BUFX1 cfg_reg_qs_b3 (.A(cfg_reg_qs_n2), .Y(cfg_reg_qs_n3));
  BUFX1 cfg_reg_qs_b4 (.A(cfg_reg_qs_n3), .Y(cfg_reg_qs_n4));
  BUFX1 cfg_reg_qs_b5 (.A(cfg_reg_qs_n4), .Y(cfg_reg_qs_n5));
  BUFX1 cfg_reg_qs_b6 (.A(cfg_reg_qs_n5), .Y(cfg_reg_qs_n6));
  BUFX1 cfg_reg_qs_b7 (.A(cfg_reg_qs_n6), .Y(cfg_reg_qs_n7));
  BUFX1 cfg_reg_qs_b8 (.A(cfg_reg_qs_n7), .Y(mode_reg_d));
  BUFX1 cfg_reg_dp_b0 (.A(cfg_reg_q), .Y(cfg_reg_dp_n0));
  BUFX1 cfg_reg_dp_b1 (.A(cfg_reg_dp_n0), .Y(data_reg_d));
endmodule
