#!/usr/bin/env python3
"""Stage-2 deterministic summary-evidence generator (p14 workflow handoff, evidence_steps=2).

Depends on stage 1: reads evidence_manifest.json (the stage-1 product) and binds its report_digest as
upstream_evidence_digest. Runs a SECOND PrimeTime analysis (the cap_reg->acc_reg register path) via
evidence_signoff_stage2.tcl, captures the real report body, canonicalizes it (same rule as stage 1),
and writes stage2_summary.json. run_nonce_stage2 folds in BOTH the stage-2 report digest AND the
stage-1 upstream digest, so a stale/missing/wrong-package stage 1 changes the stage-2 nonce -> the
hidden re-run rejects it. No wall-clock.
"""
from __future__ import annotations
import hashlib, json, os, re, subprocess


def sha_file(path):
    try:
        with open(path, "rb") as f:
            return hashlib.sha256(f.read()).hexdigest()
    except OSError:
        return ""


def jget(path, key, default=""):
    try:
        t = open(path).read()
    except OSError:
        return default
    m = re.search(r'"' + re.escape(key) + r'"\s*:\s*"([^"]*)"', t)
    return m.group(1) if m else default


def jload(path):
    try:
        return json.load(open(path))
    except (OSError, ValueError):
        return {}


_VOLATILE = re.compile(
    r"(?i)\b(date|version|copyright|license|synopsys|solvnet|report_timing|"
    r"design\s*:\s|tool created|loading|information:|warning:)\b")


def canon_report(body):
    out = []
    for line in body.splitlines():
        s = re.sub(r"\s+", " ", line).strip()
        if not s or _VOLATILE.search(s):
            continue
        out.append(s)
    return "\n".join(out) + "\n"


def main():
    pt = os.environ.get("EDA_PT_CMD", "pt_shell")
    flow = "flow_config.json"
    consumed = jget(flow, "netlist")
    top = jget(flow, "top_module", "acc_stage")
    sdc = jget(flow, "constraints", "constraints.sdc")
    scenario = jget(flow, "scenario", "func")
    corner = jget(flow, "corner", "typ")
    stage1 = jload("evidence_manifest.json")
    upstream = stage1.get("report_digest") if stage1 else None
    stage1_ok = bool(stage1) and stage1.get("signoff") == "OK" and bool(upstream)

    with open("selected.tcl", "w") as f:
        f.write('set sel "%s"\nset top "%s"\nset sdc "%s"\n' % (consumed, top, sdc))
    raw = subprocess.run([pt, "-f", "evidence_signoff_stage2.tcl"],
                         capture_output=True, text=True, timeout=600).stdout
    s2_signoff, s2_paths, s2_slack = "FAIL", 0, "NONE"
    for line in raw.splitlines():
        if line.startswith("EVFACT2_SIGNOFF"):
            s2_signoff = line.split(None, 1)[1].strip()
        elif line.startswith("EVFACT2_PATHS"):
            try:
                s2_paths = int(line.split(None, 1)[1].strip())
            except (ValueError, IndexError):
                s2_paths = 0
        elif line.startswith("EVFACT2_SLACK"):
            s2_slack = line.split(None, 1)[1].strip()
    try:
        s2_body = canon_report(open("report_body2.txt").read())
    except OSError:
        s2_body = "\n"
    stage2_report_digest = hashlib.sha256(s2_body.encode()).hexdigest()

    ih = {
        "flow_config.json": sha_file("flow_config.json"),
        "constraints.sdc": sha_file(sdc),
        "consumed_netlist": sha_file(consumed) if consumed else "",
    }
    clk = stage1.get("selected_clock", "") if stage1 else ""
    nonce_src = (ih["flow_config.json"] + ih["constraints.sdc"] + ih["consumed_netlist"]
                 + clk + scenario + corner + stage2_report_digest + (upstream or ""))
    run_nonce2 = hashlib.sha256(nonce_src.encode()).hexdigest()[:16]
    summary = {
        "_comment": "Generated by run_evidence_stage2.sh from the stage-1 evidence. Do not hand-edit. "
                    "upstream_evidence_digest binds the FRESH stage-1 report; run_nonce is deterministic.",
        "stage": "stage2",
        "upstream_evidence_digest": upstream,
        "upstream_stage_ok": stage1_ok,
        "input_hashes": ih,
        "selected_netlist": consumed,
        "selected_clock": clk,
        "scenario": scenario,
        "corner": corner,
        "tool": "pt_shell",
        "tool_exit": 0,
        "signoff": s2_signoff,
        "stage2_constrained_paths": s2_paths,
        "stage2_slack": s2_slack,
        "stage2_report_digest": stage2_report_digest,
        "run_nonce": run_nonce2,
    }
    with open("stage2_summary.json", "w") as f:
        json.dump(summary, f, indent=2, sort_keys=True)
        f.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
