#!/usr/bin/env python3
"""Stage-1 deterministic evidence generator (p14 workflow handoff).

Identical mechanism to p13 gen_evidence.py: parse flow_config.json, sign off the consumed netlist,
capture the REAL report_timing body via redirect, canonicalize it, and write
timing_report.rpt + evidence_manifest.json. Adds manifest fields stage="stage1" and
upstream_evidence_digest=null (the chain root). No wall-clock; run_nonce is a pure function of inputs
+ tool result. Shared IDENTICALLY by the public stage-1 runner and the hidden re-run.
"""
from __future__ import annotations
import hashlib, json, os, re, subprocess


def sha_file(path):
    try:
        with open(path, "rb") as f:
            return hashlib.sha256(f.read()).hexdigest()
    except OSError:
        return ""


def jget(path, key, default=""):
    try:
        t = open(path).read()
    except OSError:
        return default
    m = re.search(r'"' + re.escape(key) + r'"\s*:\s*"([^"]*)"', t)
    return m.group(1) if m else default


def sdc_clock(sdc_path):
    try:
        for line in open(sdc_path):
            line = line.strip()
            if line.startswith("create_clock"):
                m = re.search(r"-name\s+(\S+)", line)
                if m:
                    return m.group(1).strip('{}"')
    except OSError:
        pass
    return ""


_VOLATILE = re.compile(
    r"(?i)\b(date|version|copyright|license|synopsys|solvnet|report_timing|"
    r"design\s*:\s|tool created|loading|information:|warning:)\b")


def canon_report(body):
    out = []
    for line in body.splitlines():
        s = re.sub(r"\s+", " ", line).strip()
        if not s or _VOLATILE.search(s):
            continue
        out.append(s)
    return "\n".join(out) + "\n"


def main():
    pt = os.environ.get("EDA_PT_CMD", "pt_shell")
    flow = "flow_config.json"
    consumed = jget(flow, "netlist")
    top = jget(flow, "top_module", "acc_stage")
    sdc = jget(flow, "constraints", "constraints.sdc")
    scenario = jget(flow, "scenario", "func")
    corner = jget(flow, "corner", "typ")
    with open("selected.tcl", "w") as f:
        f.write('set sel "%s"\nset top "%s"\nset sdc "%s"\n' % (consumed, top, sdc))
    raw = subprocess.run([pt, "-f", "evidence_signoff.tcl"],
                         capture_output=True, text=True, timeout=600).stdout
    signoff, paths, slack = "FAIL", 0, "NONE"
    for line in raw.splitlines():
        if line.startswith("EVFACT_SIGNOFF"):
            signoff = line.split(None, 1)[1].strip()
        elif line.startswith("EVFACT_PATHS"):
            try:
                paths = int(line.split(None, 1)[1].strip())
            except (ValueError, IndexError):
                paths = 0
        elif line.startswith("EVFACT_SLACK"):
            slack = line.split(None, 1)[1].strip()
    try:
        report_body = canon_report(open("report_body.txt").read())
    except OSError:
        report_body = "\n"
    clk = sdc_clock(sdc)
    with open("timing_report.rpt", "w") as f:
        f.write("# acc_stage stage-1 evidence (generated by run_evidence_stage1.sh -- do not hand-edit)\n")
        f.write("# consumed_netlist=%s clock=%s scenario=%s corner=%s signoff=%s paths=%d slack=%s\n"
                % (consumed, clk, scenario, corner, signoff, paths, slack))
        f.write("=== REPORT_TIMING BEGIN ===\n")
        f.write(report_body)
        f.write("=== REPORT_TIMING END ===\n")
    report_digest = hashlib.sha256(report_body.encode()).hexdigest()
    ih = {
        "flow_config.json": sha_file("flow_config.json"),
        "constraints.sdc": sha_file(sdc),
        "consumed_netlist": sha_file(consumed) if consumed else "",
    }
    nonce_src = (ih["flow_config.json"] + ih["constraints.sdc"] + ih["consumed_netlist"]
                 + clk + scenario + corner + report_digest)
    run_nonce = hashlib.sha256(nonce_src.encode()).hexdigest()[:16]
    manifest = {
        "_comment": "Generated by run_evidence_stage1.sh. Do not hand-edit; the grader re-runs the "
                    "generator and compares. run_nonce is deterministic (no wall-clock).",
        "stage": "stage1",
        "upstream_evidence_digest": None,
        "input_hashes": ih,
        "selected_netlist": consumed,
        "selected_sdc": sdc,
        "selected_clock": clk,
        "scenario": scenario,
        "corner": corner,
        "tool": "pt_shell",
        "tool_exit": 0,
        "signoff": signoff,
        "constrained_paths": paths,
        "report_digest": report_digest,
        "run_nonce": run_nonce,
    }
    with open("evidence_manifest.json", "w") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
