// Gate-level netlist for rf_front — timed by PrimeTime against tiny.db
module rf_front (clk, gain_in, band_out, samp_out);
  input clk;
  input gain_in;
  output band_out;
  output samp_out;
  wire gain_reg_q;
  wire band_reg_d;
  wire samp_reg_d;
  wire gain_reg_qs_n0;
  wire gain_reg_qs_n1;
  wire gain_reg_qs_n2;
  wire gain_reg_qs_n3;
  wire gain_reg_qs_n4;
  wire gain_reg_qs_n5;
  wire gain_reg_qs_n6;
  wire gain_reg_qs_n7;
  wire gain_reg_qs_n8;
  wire gain_reg_qs_n9;
  wire gain_reg_qs_n10;
  wire gain_reg_qs_n11;
  wire gain_reg_qs_n12;
  DFFX1 gain_reg (.D(gain_in), .CK(clk), .Q(gain_reg_q));
  DFFX1 band_reg (.D(band_reg_d), .CK(clk), .Q(band_out));
  DFFX1 samp_reg (.D(samp_reg_d), .CK(clk), .Q(samp_out));
  BUFX1 gain_reg_qs_b0 (.A(gain_reg_q), .Y(gain_reg_qs_n0));
  BUFX1 gain_reg_qs_b1 (.A(gain_reg_qs_n0), .Y(gain_reg_qs_n1));
  BUFX1 gain_reg_qs_b2 (.A(gain_reg_qs_n1), .Y(gain_reg_qs_n2));
  BUFX1 gain_reg_qs_b3 (.A(gain_reg_qs_n2), .Y(gain_reg_qs_n3));
  BUFX1 gain_reg_qs_b4 (.A(gain_reg_qs_n3), .Y(gain_reg_qs_n4));
  BUFX1 gain_reg_qs_b5 (.A(gain_reg_qs_n4), .Y(gain_reg_qs_n5));
  BUFX1 gain_reg_qs_b6 (.A(gain_reg_qs_n5), .Y(gain_reg_qs_n6));
  BUFX1 gain_reg_qs_b7 (.A(gain_reg_qs_n6), .Y(gain_reg_qs_n7));
  BUFX1 gain_reg_qs_b8 (.A(gain_reg_qs_n7), .Y(gain_reg_qs_n8));
  BUFX1 gain_reg_qs_b9 (.A(gain_reg_qs_n8), .Y(gain_reg_qs_n9));
  BUFX1 gain_reg_qs_b10 (.A(gain_reg_qs_n9), .Y(gain_reg_qs_n10));
  BUFX1 gain_reg_qs_b11 (.A(gain_reg_qs_n10), .Y(gain_reg_qs_n11));
  BUFX1 gain_reg_qs_b12 (.A(gain_reg_qs_n11), .Y(gain_reg_qs_n12));
  BUFX1 gain_reg_qs_b13 (.A(gain_reg_qs_n12), .Y(band_reg_d));
  BUFX1 gain_reg_dp_b0 (.A(gain_reg_q), .Y(samp_reg_d));
endmodule
